# Requirements
<!-- 
An idea of what is required to make the project actually happen
-->

## People
<!--
Who needs to be involved, what's the proposed structure, what will it take to get their involvement?
-->
Locke Data Ltd will take on the technical work. Locke Data's primary lead for this work will be Steph Locke. Steph is a founder of
satRdays and managed the centralized infrastructure since its inception. Locke Data anticpates using freelancers and sub-contractors for some of the work where it is outside of Steph's skillset.

The core evaluation team will consist of UseR! and R Foundation team members. Heather Turner and Julie Josse have both been local organisers and program chairs of useR!. Torben Tvedebrink was local organiser of useR! 2015 and managed the development of the abstract handling software used in 2015 and 2016. Torsten Hothorn and Achim Zeileis are the permanent members of the R Foundation Conference Committee and founders of useR!.

Additional members of the community may be consulted for further testing and advice.

## Processes
<!-- 
What processes need to be put in place e.g. codes of conduct, regular ISC meetings, handover to the community at large?
-->
A contributor code of conduct will be adopted to govern the work of the team and
future work on the conference management system.

Any development of the CMS itself will be contributed back to the open source 
project for all to use. Development of content specific to the useR! or satRdays
conferences will be owned by the Consortium for the purpose of running and 
maintaining the CMS.

Members of the ISC would be invited to join the review meetings towards the end 
of the evaluation and development stages.

## Tools & Tech
<!--
What is going to be needed to deliver this project? 

Will cloud computing be used - if yes are there are necessary components that will be deciding factors between providers?

Are there tools or tech that don't exist that will be produced to facilitate the project?
-->
 - GitHub for team collaboration (public)
 - Each CMS
 - Hosting of test systems
 - Hosting of development system
 - Hosting of production system
 
The hosting of the test, development, and productions systems may require 
different resources due to the number of people accessing the system and the 
amount of content added to the system. 

## Funding
<!--
A summary of the requirements that contextualises the costs
-->
### Total funding cost
The total requested amount for this project is **$38,750**. This is primarily development costs and the breakdown of the figures are below.

### Development costs
The main cost is for the development work associated in evaluating and then implementing an R conference system.

This work is broken down into milestones, reflecting the project stages outlined in the Technical Delivery section. The hourly rate of $100, used in previous R Consortium sponsored projects like R Hubs has been used for arriving at costs, based on conservative time estimates for the project. 

In addition, an honorarium fund is requested to allow us to recognise the evaluation team (and any community contributor's).


| Item | Cost (USD) |
| ---- | ----:|
| Milestone 1: Evaluation of CMS | $15,000  |
| Milestone 2: Development of CMS | $13,500 |
| Milestone 3: Handover to useR!/satRdays | $3,750 |
| Honorarium fund | $5,000 |
| **Total** | **$37,250** |


### Hosting

New sites will need to be created for the test and development systems, 
and the cost is anticipated to be around $500 to have multiple CMS systems running for evaluation purposes.

Ongoing, we will assume a $1,000 annual consolidated cost for hosting but some or all conferences may prefer to use their funding lines to run their own instances of the software.

| Item | Cost (USD) |
| ---- | ----:|
| Project hosting | $500  |
| Annual hosting | $1000 |
| **Total** | **$1,500** |