# Success
<!-- 
Projects should have a definition of done that is measurable, and a thorough understanding going in of what the risks are to delivery 
-->

## Measuring success
<!-- 
What does success look like? 
How will we know when success is achieved, what markers can we use along the way 
-->
The project will deliver a new CMS for R Consortium supported conferences and supporting documentation to facilitate future administration and development.

The milestones for the project are 

  1. Evaluate candidate CMS software and select the best one to take forward.
  2. Set up the chosen CMS ready for use by useR! and satRdays.
  3. Handover to the organizers of useR! and satRdays.

## Future work
<!-- 
How could this be extended / developed in the future by yourself and/or the community in general?
-->
The project may identify deficiencies in the CMS that could be addressed by 
further development of the CMS itself. Alternatively integration with 
other services, for example for personalised schedules, could be explored.

Although the system will have been extensively tested during evaluation and 
development, no doubt some issues will arise during the first useR! and 
satRday using the system and there would be ongoing maintenance of the system.
We foresee such work being handled by the conference organizers, however new 
funding may be required for more substantial work such as upgrading the CMS.

Future projects could also address other common needs of R Consortium 
supported conferences. The R Foundation is currently reviewing issues faced 
by useR! organizers and this review may inform such projects.

## Key risks
<!-- 
What sort of things could come up that can delay or break the project?

 - [ ] People
 - [ ] Processes
 - [ ] Tooling & Technology
 - [ ] Costs

-->
Locke Data will be responsible for the successful delivery of this project. Locke Data anticipate using freelancers on a third of the work for the project. If more work needs to be done by freelancers, then the time to recruit people could cause delays.

It is possible that some obstacle would be meet in attempting to set up a 
particular CMS. If this could not be overcome, this would simply eliminate the
CMS from the evaluation. Since we have a good set of candidates, we are 
confident that at least one can be selected as suitable CMS for useR! and
satRdays, even if it does not implement everything on our wish list.

The main cost is associated with setting up each CMS and developing the
selected CMS. We would prioritise the four candidates, so that if the evaluation 
phase took longer than expected, we could consider at least three CMS. If 
the development phase takes longer than expected this could run into the 
handover time, if necessary passing more of the conference-specific setup onto 
organizers. The proposed timeline aims to handover in July, 
when useR! 2017 will only just have taken place. Thus a delay of one or even two 
months could be accommodated with minimal effect on the organization of the
next conference.
