# Project plan

## Start-up phase

<!--
Covering the planning phase, this section should provide a relatively detailed plan of how work will start on the project. This section is important because projects need to get up and running quickly.


 - [ ] Setting up collaboration platform inc. code for contributors etc.
 - [ ] Licence decisions
 - [ ] Reporting framework
-->

A GitHub repository will be set up for us to collaboratively work on documents
summarising our evaluation of the different systems. The CMS software
will be prioritised to consider most promising candidates first. We will write
a post for the R Consortium blog to announce our project.

## Technical delivery
<!--
Covering the actual delivery of the project this section should provide at least a high-level the implementation. 

Including target dates is really important as you need to be committed and the ISC need to have a means of tracking delivery
-->

### Evaluation Stage (Mid March - End April)

We will work through each CMS in turn, with the work divided as follows:

 - Locke Data: Set up test system; consider general issues such 
 as security, accessibility, ability to set up recurring events and handle 
 multiple conferences
 - Evaluation team: Rotate through the following roles and collaboratively edit
 document on pros/cons of system
    - Participant 1: submit abstract, edit abstract, contact local organizer
    - Participant 2: submit abstract, register
    - Program chair: assign abstracts to reviewers, make final decision, 
    schedule presentations, assign chairs
    - Reviewer 1: ask for first abstract to be reassigned (to Reviewer 2), 
    review second abstract, make recommendation
    - Reviewer 2: review first abstract, make recommendation, suggest session 
    for abstract, see if there is a way to group with second abstract
    - Local organizer - email registered participants, add information to the
    conference website
    
Locke Data will round up the pros/cons of each CMS and the full team will meet to 
make a decision on which CMS to take forward. Some 
queries may need to be followed up by Locke Data to come to a final decision.

*Estimated work time: 20 days (Locke Data); 10 hours each (evaluation team).*

### Development Stage (May - June)

Having decided on a CMS, Locke Data will work on putting the system into production, ready for use by useR! 2018 and the next satRdays. This will include creating standard text where possible e.g. for abstract submission instructions, and creating templates that reuse parameters, e.g. abstract submission deadlines.

Given previous experience of testing each CMS, the full team will decide how best to test the system. Members of the community may be invited to comment on the website and to test the system, in particular this may be necessary to fully test accessibility for the visually impaired. A post on the R Consortium blog announcing the delivery of a beta system would be an opportunity to invite testers.

Locke Data will make adjustments in response to the testing. Larger changes - requiring extensions to the system itself - may need to be addressed in a separate project.

*Estimated work time: 18 days (Locke Data); 8 hours each (evaluation team).*

### Production Stage (July - )

Locke Data will work with the organizers of useR! 2018 and the next satRdays to 
provide support in using the new system and make any necessary adjustments.

*Estimated work time: 5 days (Locke Data).*
